//  1 未激活 2 激活 3 挂起
const STATUS_READY = 0;
const STATUS_ACTIVE = 1;
const STATUS_HANG = 2;

const STATUS_TEXT = {};
STATUS_TEXT[STATUS_READY] = '未激活';
STATUS_TEXT[STATUS_ACTIVE] = '激活';
STATUS_TEXT[STATUS_HANG] = '挂起';

const STATUS_BTN_TEXT = {}; 
STATUS_BTN_TEXT[STATUS_READY] = '激活';
STATUS_BTN_TEXT[STATUS_ACTIVE] = '挂起';
STATUS_BTN_TEXT[STATUS_HANG] = '激活';

export {STATUS_READY}
export {STATUS_ACTIVE}
export {STATUS_HANG}
export {STATUS_TEXT}
export {STATUS_BTN_TEXT}